projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
  db:
    schemaPath: src/generated/prisma.graphql
    extensions:
      endpoints:
        default: http://localhost:4466/video
      prisma: prisma/prisma.yml
      codegen:
        output:
          typings: src/generated/prisma.ts
        generator: typegen
        language: typescript