version: '3'
services:
  rsync:
    build: ./docker-image/rsync-deploy
    restart: always
    ports:
      - "2222:22"
      - "9080:80"
    environment:
    # http://172.16.18.99/malik.l.keys
      DEPLOY_KEY_URL: https://github.com/stoneli88.keys
    volumes:
      - rsync:/rsync
  redis:
    image: 'bitnami/redis:latest'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis'
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
            migrations: true
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
    driver: local
  redis_data:
    driver: local
  rsync:
    driver: local
    driver_opts:
         type: None
         device: $HOME/Work/tmp/rsync
         o: bind