#!/bin/sh

if ! [ -f /etc/ssh/keys/ssh_host_dsa_key ]; then
  ssh-keygen -f /etc/ssh/keys/ssh_host_dsa_key -N '' -t dsa
fi

if ! [ -f /etc/ssh/keys/ssh_host_rsa_key ]; then
  ssh-keygen -f /etc/ssh/keys/ssh_host_rsa_key -N '' -t rsa
fi

if ! [ -f /etc/ssh/keys/ssh_host_ecdsa_key ]; then
  ssh-keygen -f /etc/ssh/keys/ssh_host_ecdsa_key -N '' -t ecdsa
fi
